### ISSUE TITLE
LateInitializationError on _toIsolate field

### ISSUE THREAD

**Issue by cedarbob** [raj457036/simple_worker#1]
I created a basic worker using a static function with signature void _updateScene(double dt, Sender send) passed to the Entrypoint constructor.  I await on a call to waitUntilReady, then try to send my first message to the isolate.  My app dies with the error:
Unhandled Exception: LateInitializationError: Field '_toIsolate@60227773' has not been initialized

**Comment by raj457036** [comment]
Could you please add the code snippet.

**Comment by raj457036** [comment]
Fixed in version 1.0.1
